# Generated by Django 3.1 on 2020-09-29 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_auto_20200929_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
