# Generated by Django 3.1 on 2020-09-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_auto_20200929_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.RemoveField(
            model_name='book',
            name='created',
        ),
    ]
